page-admin:
    path: /admin/
    controller: App\Controller\Page\IndexController::admin
page-front:
    path: /front/
    controller: App\Controller\Page\IndexController::front
page-front-out:
    path: /front-out/
    controller: App\Controller\Page\IndexController::frontOut
page-user:
    path: /
    controller: App\Controller\Page\IndexController::user
page-user-mine:
    path: /user/mine
    controller: App\Controller\Page\IndexController::userMine
page-signin:
    path: /signin
    controller: App\Controller\Page\IndexController::signin
page-register:
    path: /reg
    controller: App\Controller\Page\IndexController::register
